/**
 * employee.model.ts
 *
 * Defines the Employee interface that mirrors the Java Entity class on the backend.
 * All fields are optional (except id on updates) to support both create and edit flows:
 *  - id         → auto-generated by the backend (GenerationType.AUTO); omitted on POST
 *  - name       → required (@NotNull on backend)
 *  - department → free-text string
 *  - salary     → must be >= 5500.00 (@DecimalMin on backend)
 *  - designation→ free-text string
 */
export interface Employee {
  id?: number;           // Optional: not sent on create, returned by backend on save
  name: string;          // Required: maps to @NotNull in Java entity
  department: string;    // Maps to employees.department column
  salary: number;        // Must be >= 5500.00 (validated on backend)
  designation: string;   // Maps to employees.designation column
}
