// employee.model.ts
// Mirrors the Employee Java entity class on the backend.
export interface Employee {
  id?:          number;    // Optional: auto-generated by the database
  name:         string;    // @NotNull on backend – required
  department:   string;
  salary:       number;    // @DecimalMin("5500.00") on backend
  designation:  string;
}
