/**
 * employee.service.ts
 *
 * Angular service that encapsulates all HTTP calls to the Spring Boot REST API.
 * Base URL targets the backend running on localhost:8080 (see application.properties).
 *
 * Maps to EmployeeController.java endpoints:
 *  GET    /api/employees       → getAllEmployees()
 *  GET    /api/employees/:id   → getEmployeeById()
 *  POST   /api/employees       → createEmployee()
 *  PUT    /api/employees/:id   → updateEmployee()
 *  DELETE /api/employees/:id   → deleteEmployee()
 *
 * All methods return Observables so components can subscribe and react to async results.
 */

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Employee } from '../models/employee.model';

@Injectable({
  providedIn: 'root'   // Singleton: one instance shared across the whole app
})
export class EmployeeService {

  /** Base URL pointing to the Spring Boot backend */
  private readonly API_URL = 'http://localhost:8080/api/employees';

  /** HttpClient is injected by Angular's DI system */
  constructor(private http: HttpClient) {}

  /**
   * GET /api/employees
   * Fetches the full list of employees.
   * Maps to: EmployeeController.getAllEmployees()
   */
  getAllEmployees(): Observable<Employee[]> {
    return this.http.get<Employee[]>(this.API_URL);
  }

  /**
   * GET /api/employees/:id
   * Fetches a single employee by primary key.
   * Maps to: EmployeeController.getEmployeeById()
   * @param id - The employee's auto-generated Long id
   */
  getEmployeeById(id: number): Observable<Employee> {
    return this.http.get<Employee>(`${this.API_URL}/${id}`);
  }

  /**
   * POST /api/employees
   * Creates a new employee record. Backend returns 201 CREATED with the saved entity.
   * Maps to: EmployeeController.createEmployee()
   * @param employee - Employee object without an id (id is generated by the database)
   */
  createEmployee(employee: Employee): Observable<Employee> {
    return this.http.post<Employee>(this.API_URL, employee);
  }

  /**
   * PUT /api/employees/:id
   * Fully replaces an existing employee record.
   * Maps to: EmployeeController.updateEmployee()
   * @param id       - The id of the employee to update
   * @param employee - Full updated Employee object (all fields required by backend)
   */
  updateEmployee(id: number, employee: Employee): Observable<Employee> {
    return this.http.put<Employee>(`${this.API_URL}/${id}`, employee);
  }

  /**
   * DELETE /api/employees/:id
   * Removes an employee record. Backend returns a plain-text success/error message.
   * Maps to: EmployeeController.deleteEmployee()
   * @param id - The id of the employee to delete
   */
  deleteEmployee(id: number): Observable<string> {
    // responseType: 'text' because the backend returns a plain String, not JSON
    return this.http.delete(`${this.API_URL}/${id}`, { responseType: 'text' });
  }
}
