spring.application.name=webdemo

# H2 SETTINGS
#Database Configuration 
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:datajpa;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# Ensures data.sql runs AFTER Hibernate has created the tables
spring.jpa.defer-datasource-initialization=true 
#enabling the H2 console  
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
